In [1]:
import requests
import pandas as pd
from pathlib import Path
import os

In [2]:
headers = {"User-Agent": "Zain zain@unicusresearch.com"}
headers_submissions = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}

# Ticker of Companies on SEC

In [3]:
url_sec_companies = "https://www.sec.gov/files/company_tickers.json"
resp_sec_companies = requests.get(url=url_sec_companies, headers=headers)

resp_sec_companies.status_code

200

In [4]:
df_sec_companies = pd.DataFrame(resp_sec_companies.json().values())
df_sec_companies

       cik_str   ticker                      title
0      1045810     NVDA                NVIDIA CORP
1       320193     AAPL                 Apple Inc.
2      1652044    GOOGL              Alphabet Inc.
3       789019     MSFT             MICROSOFT CORP
4      1018724     AMZN             AMAZON COM INC
...        ...      ...                        ...
10421  2083217    QADRW     QDRO Acquisition Corp.
10422  2083632    OCTLF    Octave Intelligence plc
10423  2083217    QADRU     QDRO Acquisition Corp.
10424  2080023  VACI-UN  Viking Acquisition Corp I
10425  2080023  VACI-WT  Viking Acquisition Corp I

[10426 rows x 3 columns]

In [5]:
company_ticker = "OKLO"
company_cik = str(list(df_sec_companies[df_sec_companies["ticker"]==company_ticker]["cik_str"])[0]).zfill(10)
company_cik

'0001849056'

# Ticker of Funds on SEC
Non traded funds like CCLFX registered with SEC but not listed on any exchange, so they won't appear in either ticker mapping file and have to directly find their cik via edgar

In [6]:
url_sec_funds = "https://www.sec.gov/files/company_tickers_mf.json"
resp_sec_funds = requests.get(url_sec_funds, headers=headers)

resp_sec_funds.status_code

200

In [7]:
json_sec_funds = resp_sec_funds.json()
df_sec_funds = pd.DataFrame(json_sec_funds["data"], columns=json_sec_funds["fields"])
df_sec_funds

           cik    seriesId     classId symbol
0         2110  S000009184  C000024954  LACAX
1         2110  S000009184  C000024956  LIACX
2         2110  S000009184  C000024957  ACRNX
3         2110  S000009184  C000122736  CRBRX
4         2110  S000009184  C000122737  CRBYX
...        ...         ...         ...    ...
28396  2081199  S000105287  C000276035   BROL
28397  2083193  S000097445  C000266630   FEMD
28398  2083193  S000097446  C000266631   USFE
28399  2096904  S000101078  C000271016   MHIG
28400  2096904  S000101079  C000271017   MHIP

[28401 rows x 4 columns]

In [8]:
fund_ticker = "CCLFX"
fund_cik = str(df_sec_funds[df_sec_funds["symbol"]==fund_ticker]["cik"].values[0]).zfill(10)
fund_cik

IndexError: index 0 is out of bounds for axis 0 with size 0

In [9]:
fund_ticker = "CCLFX"
fund_cik = str(df_sec_funds[df_sec_funds["symbol"]==fund_ticker])
fund_cik

'Empty DataFrame\nColumns: [cik, seriesId, classId, symbol]\nIndex: []'

# Submissions by a company

In [10]:
# company_cik = "0001658645"
# company_cik = "0001735964"
company_cik = '0001842754'

In [11]:
url_submissions = f"https://data.sec.gov/submissions/CIK{company_cik}.json"
resp_submissions = requests.get(url_submissions, headers=headers)
print(resp_submissions.status_code)

json_submissions = resp_submissions.json()

200

In [12]:
json_submissions

{'cik': '0001842754',
 'entityType': 'other',
 'sic': '',
 'sicDescription': '',
 'ownerOrg': '',
 'insiderTransactionForOwnerExists': 0,
 'insiderTransactionForIssuerExists': 1,
 'name': 'Cliffwater Enhanced Lending Fund',
 'tickers': [],
 'exchanges': [],
 'ein': '000000000',
 'lei': None,
 'description': '',
 'website': '',
 'investorWebsite': '',
 'category': '',
 'fiscalYearEnd': '0331',
 'stateOfIncorporation': 'DE',
 'stateOfIncorporationDescription': 'DE',
 'addresses': {'mailing': {'street1': 'C/O UMB FUND SERVICES, INC.',
   'street2': '235 WEST GALENA STREET',
   'city': 'MILWAUKEE',
   'stateOrCountry': 'WI',
   'zipCode': '53212',
   'stateOrCountryDescription': 'WI',
   'isForeignLocation': 0,
   'foreignStateTerritory': None,
   'country': None,
   'countryCode': None},
  'business': {'street1': 'C/O UMB FUND SERVICES, INC.',
   'street2': '235 WEST GALENA STREET',
   'city': 'MILWAUKEE',
   'stateOrCountry': 'WI',
   'zipCode': '53212',
   'stateOrCountryDescription': 'WI',
   'isForeignLocation': None,
   'foreignStateTerritory': None,
   'country': None,
   'countryCode': None}},
 'phone': '414-299-2270',
 'flags': '',
 'formerNames': [],
 'filings': {'recent': {'accessionNumber': ['0001213900-26-072003',
    '0001842754-26-000008',
    '0001213900-26-067666',
    '0001213900-26-066323',
    '0001842754-26-000004',
    '0001213900-26-053688',
    '0001213900-26-032404',
    '0001193125-26-080327',
    '0001213900-26-015940',
    '0001213900-26-003846',
    '0001213900-25-118509',
    '0001193125-25-295461',
    '0001213900-25-109689',
    '0001213900-25-100762',
    '0001213900-25-086827',
    '0001213900-25-084438',
    '0001145549-25-055662',
    '0001213900-25-080991',
    '0001213900-25-076169',
    '0001104659-25-074664',
    '0001213900-25-070484',
    '0001213900-25-068754',
    '0001104659-25-067819',
    '0001213900-25-057679',
    '0001145549-25-040034',
    '0001213900-25-052549',
    '0001213900-25-049315',
    '0001145549-25-037155',
    '0001213900-25-049198',
    '0001213900-25-043767',
    '0001213900-25-041664',
    '0001213900-25-028883',
    '0001145549-25-015524',
    '0001213900-25-009170',
    '0001213900-25-004654',
    '0001213900-24-106844',
    '0001145549-24-076941',
    '0001839882-24-040858',
    '0001213900-24-090223',
    '0001213900-24-079857',
    '0001213900-24-073841',
    '0001145549-24-055433',
    '0001013762-24-002024',
    '0001013762-24-001956',
    '0001999371-24-008869',
    '0001213900-24-056681',
    '0001145549-24-037090',
    '0001213900-24-050670',
    '0001145549-24-035063',
    '0001213900-24-036894',
    '0001145549-24-012963',
    '0001213900-24-009398',
    '0001213900-23-094292',
    '0001145549-23-073450',
    '0001104659-23-121025',
    '0001104659-23-113863',
    '0001104659-23-112505',
    '0001013762-23-007100',
    '0001213900-23-076098',
    '0001213900-23-072666',
    '0001145549-23-053969',
    '0001213900-23-060471',
    '0001213900-23-060229',
    '0001387131-23-008697',
    '0001213900-23-052728',
    '0001145549-23-036982',
    '0001213900-23-047761',
    '0001145549-23-031925',
    '0001213900-23-034235',
    '0001145549-23-014032',
    '0001398344-23-001873',
    '0001398344-22-024397',
    '0001145549-22-070418',
    '0001398344-22-020798',
    '0001398344-22-020098',
    '0001398344-22-020006',
    '0001398344-22-018390',
    '0001398344-22-017987',
    '0001398344-22-017617',
    '0001145549-22-054827',
    '0001398344-22-014226',
    '0001398344-22-012678',
    '0001398344-22-012224',
    '0001145549-22-036734',
    '0001398344-22-011833',
    '0001145549-22-032057',
    '0001398344-22-008240',
    '0001398344-22-006152',
    '0001145549-22-013896',
    '0001104659-22-020859',
    '0001104659-22-020337',
    '0001398344-22-000215',
    '0001398344-21-023692',
    '0001145549-21-068781',
    '0001398344-21-021891',
    '0001398344-21-020998',
    '0001398344-21-020130',
    '0001213900-21-041304',
    '0001213900-21-041302',
    '0001213900-21-038927',
    '0001213900-21-038924',
    '0001213900-21-038919',
    '0001213900-21-038916',
    '0001398344-21-014656',
    '0001104659-21-092183',
    '0001104659-21-090607',
    '0001398344-21-013202',
    '9999999995-21-002324',
    '0001104659-21-080985',
    '0001398344-21-013094',
    '0001398344-21-013091',
    '0001398344-21-013090',
    '0001398344-21-013087',
    '0001398344-21-013086',
    '0001398344-21-013085',
    '0001398344-21-013082',
    '0001398344-21-013034',
    '0001398344-21-012996',
    '0001398344-21-013000',
    '0001398344-21-012974',
    '0001398344-21-012725',
    '0001398344-21-007889',
    '0001398344-21-007885',
    '0001398344-21-003717',
    '0001398344-21-001635',
    '0001398344-21-001624'],
   'filingDate': ['2026-06-25',
    '2026-06-12',
    '2026-06-11',
    '2026-06-08',
    '2026-05-22',
    '2026-05-08',
    '2026-03-20',
    '2026-02-27',
    '2026-02-13',
    '2026-01-13',
    '2025-12-05',
    '2025-11-25',
    '2025-11-13',
    '2025-10-21',
    '2025-09-11',
    '2025-09-04',
    '2025-08-28',
    '2025-08-27',
    '2025-08-14',
    '2025-08-06',
    '2025-08-01',
    '2025-07-29',
    '2025-07-14',
    '2025-06-25',
    '2025-06-13',
    '2025-06-09',
    '2025-05-30',
    '2025-05-30',
    '2025-05-30',
    '2025-05-15',
    '2025-05-09',
    '2025-04-04',
    '2025-02-28',
    '2025-02-03',
    '2025-01-17',
    '2024-12-09',
    '2024-11-29',
    '2024-11-22',
    '2024-10-24',
    '2024-09-18',
    '2024-08-29',
    '2024-08-29',
    '2024-07-29',
    '2024-07-29',
    '2024-07-22',
    '2024-06-27',
    '2024-06-14',
    '2024-06-07',
    '2024-05-30',
    '2024-04-29',
    '2024-02-28',
    '2024-02-02',
    '2023-12-08',
    '2023-11-28',
    '2023-11-24',
    '2023-11-02',
    '2023-10-30',
    '2023-10-27',
    '2023-09-12',
    '2023-08-31',
    '2023-08-29',
    '2023-07-28',
    '2023-07-27',
    '2023-07-26',
    '2023-06-29',
    '2023-06-14',
    '2023-06-09',
    '2023-05-25',
    '2023-05-01',
    '2023-03-01',
    '2023-02-02',
    '2022-12-09',
    '2022-11-28',
    '2022-10-27',
    '2022-10-12',
    '2022-10-11',
    '2022-09-09',
    '2022-09-02',
    '2022-08-30',
    '2022-08-29',
    '2022-07-28',
    '2022-06-29',
    '2022-06-21',
    '2022-06-14',
    '2022-06-09',
    '2022-05-26',
    '2022-04-29',
    '2022-03-22',
    '2022-03-01',
    '2022-02-14',
    '2022-02-11',
    '2022-01-06',
    '2021-12-09',
    '2021-11-24',
    '2021-11-19',
    '2021-11-05',
    '2021-10-20',
    '2021-08-10',
    '2021-08-10',
    '2021-07-27',
    '2021-07-27',
    '2021-07-27',
    '2021-07-27',
    '2021-07-21',
    '2021-07-14',
    '2021-07-09',
    '2021-06-21',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-11',
    '2021-06-11',
    '2021-06-10',
    '2021-06-10',
    '2021-06-07',
    '2021-04-09',
    '2021-04-09',
    '2021-02-18',
    '2021-01-29',
    '2021-01-29'],
   'reportDate': ['2026-03-31',
    '2026-03-31',
    '',
    '2026-03-31',
    '2026-03-31',
    '2026-05-08',
    '2026-03-18',
    '2025-12-31',
    '2026-02-13',
    '',
    '2025-09-30',
    '2025-09-30',
    '2025-11-13',
    '2025-10-15',
    '',
    '',
    '2025-06-30',
    '2025-06-30',
    '2025-08-14',
    '2025-08-04',
    '',
    '',
    '2025-07-10',
    '2025-03-31',
    '2025-03-31',
    '2025-03-31',
    '',
    '2025-03-31',
    '',
    '2025-05-15',
    '2023-11-22',
    '',
    '2024-12-31',
    '2025-02-03',
    '',
    '2024-09-30',
    '2024-09-30',
    '2024-11-20',
    '2024-10-24',
    '',
    '2024-06-30',
    '2024-06-30',
    '2024-07-29',
    '',
    '2024-07-19',
    '2024-03-31',
    '2024-03-31',
    '2024-03-31',
    '2024-03-31',
    '2024-04-29',
    '2023-12-31',
    '2024-02-02',
    '2023-09-30',
    '2023-09-30',
    '2023-11-22',
    '2023-10-26',
    '2023-10-26',
    '2023-10-27',
    '',
    '2023-06-30',
    '2023-06-30',
    '2023-07-28',
    '',
    '2023-07-24',
    '2023-03-31',
    '2023-03-31',
    '',
    '2023-03-31',
    '2023-05-01',
    '2022-12-31',
    '2023-02-02',
    '2022-09-30',
    '2022-09-30',
    '2022-10-27',
    '2022-10-07',
    '2022-10-07',
    '',
    '',
    '2022-06-30',
    '2022-06-30',
    '2022-07-28',
    '2022-03-31',
    '',
    '2022-03-31',
    '2022-03-31',
    '2022-03-31',
    '2022-04-29',
    '2022-03-18',
    '2021-12-31',
    '',
    '',
    '2022-01-06',
    '2021-09-30',
    '2021-09-30',
    '',
    '',
    '2021-10-20',
    '',
    '2021-06-30',
    '',
    '',
    '',
    '2021-06-30',
    '2021-07-21',
    '',
    '',
    '',
    '',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '2021-06-14',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''],
   'acceptanceDateTime': ['2026-06-25T19:12:04.000Z',
    '2026-06-12T17:41:32.000Z',
    '2026-06-11T15:40:42.000Z',
    '2026-06-08T20:52:20.000Z',
    '2026-05-22T18:35:56.000Z',
    '2026-05-08T16:04:31.000Z',
    '2026-03-20T20:52:57.000Z',
    '2026-02-27T16:20:13.000Z',
    '2026-02-13T14:46:48.000Z',
    '2026-01-13T20:03:02.000Z',
    '2025-12-05T15:03:49.000Z',
    '2025-11-25T15:37:36.000Z',
    '2025-11-13T15:12:25.000Z',
    '2025-10-21T19:25:07.000Z',
    '2025-09-11T20:10:24.000Z',
    '2025-09-04T18:23:09.000Z',
    '2025-08-28T16:06:51.000Z',
    '2025-08-27T16:01:49.000Z',
    '2025-08-14T14:07:30.000Z',
    '2025-08-06T19:11:29.000Z',
    '2025-08-01T17:08:29.000Z',
    '2025-07-29T20:53:48.000Z',
    '2025-07-14T22:16:58.000Z',
    '2025-06-25T17:35:43.000Z',
    '2025-06-13T18:12:42.000Z',
    '2025-06-09T18:32:52.000Z',
    '2025-05-30T17:13:29.000Z',
    '2025-05-30T14:25:01.000Z',
    '2025-05-30T13:57:19.000Z',
    '2025-05-15T13:52:36.000Z',
    '2025-05-09T23:58:33.000Z',
    '2025-04-04T16:38:16.000Z',
    '2025-02-28T21:39:28.000Z',
    '2025-02-03T16:10:32.000Z',
    '2025-01-17T21:44:31.000Z',
    '2024-12-09T19:18:29.000Z',
    '2024-11-29T14:49:06.000Z',
    '2024-11-23T00:25:39.000Z',
    '2024-10-24T15:03:19.000Z',
    '2024-09-18T19:54:42.000Z',
    '2024-08-29T19:37:07.000Z',
    '2024-08-29T16:46:51.000Z',
    '2024-07-29T19:13:41.000Z',
    '2024-07-29T17:18:19.000Z',
    '2024-07-22T16:27:14.000Z',
    '2024-06-27T20:28:40.000Z',
    '2024-06-14T16:52:56.000Z',
    '2024-06-07T18:16:42.000Z',
    '2024-05-30T18:25:28.000Z',
    '2024-04-29T13:38:07.000Z',
    '2024-02-28T22:22:37.000Z',
    '2024-02-02T15:43:38.000Z',
    '2023-12-08T17:57:18.000Z',
    '2023-11-28T21:16:57.000Z',
    '2023-11-24T21:54:43.000Z',
    '2023-11-02T21:13:57.000Z',
    '2023-10-30T18:17:11.000Z',
    '2023-10-27T14:55:10.000Z',
    '2023-09-12T20:13:58.000Z',
    '2023-08-31T14:48:47.000Z',
    '2023-08-29T15:26:00.000Z',
    '2023-07-28T14:28:03.000Z',
    '2023-07-27T19:01:52.000Z',
    '2023-07-26T14:17:13.000Z',
    '2023-06-29T15:35:17.000Z',
    '2023-06-14T18:41:40.000Z',
    '2023-06-09T18:16:55.000Z',
    '2023-05-25T19:07:03.000Z',
    '2023-05-01T14:25:34.000Z',
    '2023-03-01T16:19:58.000Z',
    '2023-02-02T15:27:39.000Z',
    '2022-12-09T20:58:38.000Z',
    '2022-11-28T15:46:00.000Z',
    '2022-10-27T15:22:03.000Z',
    '2022-10-12T22:47:36.000Z',
    '2022-10-11T19:23:02.000Z',
    '2022-09-09T21:02:32.000Z',
    '2022-09-02T19:39:40.000Z',
    '2022-08-30T21:12:03.000Z',
    '2022-08-29T20:55:06.000Z',
    '2022-07-28T17:17:10.000Z',
    '2022-06-29T20:35:13.000Z',
    '2022-06-17T22:25:50.000Z',
    '2022-06-14T18:25:25.000Z',
    '2022-06-09T21:20:53.000Z',
    '2022-05-26T14:56:48.000Z',
    '2022-04-29T14:48:57.000Z',
    '2022-03-22T18:26:07.000Z',
    '2022-03-01T21:41:38.000Z',
    '2022-02-12T01:35:57.000Z',
    '2022-02-11T19:46:16.000Z',
    '2022-01-06T15:16:23.000Z',
    '2021-12-09T20:10:19.000Z',
    '2021-11-24T15:32:32.000Z',
    '2021-11-19T18:57:00.000Z',
    '2021-11-05T18:55:06.000Z',
    '2021-10-20T17:29:16.000Z',
    '2021-08-10T15:05:00.000Z',
    '2021-08-10T15:03:01.000Z',
    '2021-07-27T21:14:14.000Z',
    '2021-07-27T21:11:47.000Z',
    '2021-07-27T21:08:19.000Z',
    '2021-07-27T21:04:52.000Z',
    '2021-07-21T21:01:48.000Z',
    '2021-07-14T21:25:51.000Z',
    '2021-07-09T19:13:25.000Z',
    '2021-06-18T00:50:49.000Z',
    '2021-06-15T04:15:35.000Z',
    '2021-06-15T00:17:37.000Z',
    '2021-06-14T23:32:38.000Z',
    '2021-06-14T21:50:18.000Z',
    '2021-06-14T21:46:20.000Z',
    '2021-06-14T21:42:53.000Z',
    '2021-06-14T21:41:27.000Z',
    '2021-06-14T21:40:30.000Z',
    '2021-06-14T21:39:28.000Z',
    '2021-06-11T20:54:02.000Z',
    '2021-06-10T22:59:31.000Z',
    '2021-06-10T23:04:10.000Z',
    '2021-06-10T19:47:50.000Z',
    '2021-06-07T20:30:17.000Z',
    '2021-04-09T20:50:29.000Z',
    '2021-04-09T20:34:29.000Z',
    '2021-02-18T21:57:22.000Z',
    '2021-01-29T02:21:59.000Z',
    '2021-01-29T00:51:54.000Z'],
   'act': ['33',
    '40',
    'IC',
    '40',
    '40',
    '40',
    '',
    '40',
    '40',
    'IC',
    '40',
    '40',
    '40',
    '',
    '33',
    '40',
    '40',
    '40',
    '40',
    '',
    '33',
    '40,33',
    '',
    '33',
    '40',
    '40',
    '40,33',
    '40',
    '33',
    '40',
    '',
    '33',
    '40',
    '40',
    '33',
    '40',
    '40',
    '',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40,33',
    '',
    '33',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '',
    '',
    '',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40,33',
    '',
    '33',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '',
    '',
    '40',
    '40,33',
    '40',
    '40',
    '40',
    '33',
    '40',
    '40',
    '40',
    '40',
    '40',
    '',
    '40',
    '34',
    '34',
    '40',
    '40',
    '40',
    '33',
    '40',
    '40',
    '34',
    '',
    '34',
    '34',
    '34',
    '',
    '40',
    '34',
    '34',
    '33',
    '33',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '40,33',
    '40,33',
    '',
    '',
    '',
    '40,33',
    '',
    '33',
    '40,33',
    '40'],
   'form': ['24F-2NT',
    'N-CEN',
    '40-APP/A',
    'N-CSR',
    'NPORT-P',
    'N-23C3A',
    '4',
    'NPORT-P',
    'N-23C3A',
    '40-APP',
    'N-CSRS',
    'NPORT-P',
    'N-23C3A',
    '3',
    '424B3',
    '40-17G',
    'NPORT-P',
    'N-PX',
    'N-23C3A',
    '4',
    '424B3',
    '486BPOS',
    '4',
    '24F-2NT',
    'N-CEN',
    'N-CSR',
    '486APOS',
    'NPORT-P',
    '424B3',
    'N-23C3A',
    '4',
    '424B3',
    'NPORT-P',
    'N-23C3A',
    '424B3',
    'N-CSRS',
    'NPORT-P',
    '4',
    'N-23C3A',
    '40-17G',
    'N-PX',
    'NPORT-P',
    'N-23C3A',
    '486BPOS',
    '4',
    '24F-2NT',
    'N-CEN',
    'N-CSR',
    'NPORT-P',
    'N-23C3A',
    'NPORT-P',
    'N-23C3A',
    'N-CSRS',
    'NPORT-P',
    '4/A',
    '4/A',
    '4',
    'N-23C3A',
    '40-17G',
    'N-PX',
    'NPORT-P',
    'N-23C3A',
    '486BPOS',
    '4',
    '24F-2NT',
    'N-CEN',
    'N-CSR',
    'NPORT-P',
    'N-23C3A',
    'NPORT-P',
    'N-23C3A',
    'N-CSRS',
    'NPORT-P',
    'N-23C3A',
    '4',
    '4',
    '40-17G',
    '486BPOS',
    'N-PX',
    'NPORT-P',
    'N-23C3A',
    '24F-2NT',
    '40-17G/A',
    'N-CEN',
    'N-CSR',
    'NPORT-P',
    'N-23C3A',
    '4',
    'NPORT-P',
    'SC 13G/A',
    'SC 13G/A',
    'N-23C3A',
    'N-CSRS',
    'NPORT-P',
    '424B3',
    '40-17G',
    'N-23C3A',
    'SC 13G',
    '3',
    'SC 13G',
    'SC 13G',
    'SC 13D',
    '3',
    'N-23C3A',
    'SC 13G',
    'SC 13G',
    '424B3',
    'EFFECT',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    'N-2/A',
    'N-2/A',
    'CORRESP',
    'CORRESP',
    'CORRESP',
    'N-2/A',
    'CORRESP',
    'DEL AM',
    'N-2',
    'N-8A'],
   'fileNumber': ['333-252528',
    '811-23630',
    '812-15973-06',
    '811-23630',
    '811-23630',
    '817-01424',
    '',
    '811-23630',
    '817-01424',
    '812-15973-06',
    '811-23630',
    '811-23630',
    '817-01424',
    '',
    '333-252528',
    '811-23630',
    '811-23630',
    '811-23630',
    '817-01424',
    '',
    '333-252528',
    '811-23630,333-252528',
    '',
    '333-252528',
    '811-23630',
    '811-23630',
    '811-23630,333-252528',
    '811-23630',
    '333-252528',
    '817-01424',
    '',
    '333-252528',
    '811-23630',
    '817-01424',
    '333-252528',
    '811-23630',
    '811-23630',
    '',
    '817-01424',
    '811-23630',
    '811-23630',
    '811-23630',
    '817-01424',
    '811-23630,333-252528',
    '',
    '333-252528',
    '811-23630',
    '811-23630',
    '811-23630',
    '817-01424',
    '811-23630',
    '817-01424',
    '811-23630',
    '811-23630',
    '',
    '',
    '',
    '817-01424',
    '811-23630',
    '811-23630',
    '811-23630',
    '817-01424',
    '811-23630,333-252528',
    '',
    '333-252528',
    '811-23630',
    '811-23630',
    '811-23630',
    '817-01424',
    '811-23630',
    '817-01424',
    '811-23630',
    '811-23630',
    '817-01424',
    '',
    '',
    '811-23630',
    '811-23630,333-252528',
    '811-23630',
    '811-23630',
    '817-01424',
    '333-252528',
    '811-23630',
    '811-23630',
    '811-23630',
    '811-23630',
    '817-01424',
    '',
    '811-23630',
    '005-92656',
    '005-92656',
    '817-01424',
    '811-23630',
    '811-23630',
    '333-252528',
    '811-23630',
    '817-01424',
    '005-92656',
    '',
    '005-92656',
    '005-92656',
    '005-92656',
    '',
    '817-01424',
    '005-92656',
    '005-92656',
    '333-252528',
    '333-252528',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '811-23630,333-252528',
    '811-23630,333-252528',
    '',
    '',
    '',
    '811-23630,333-252528',
    '',
    '333-252528',
    '811-23630,333-252528',
    '811-23630'],
   'filmNumber': ['261121225',
    '261085919',
    '261081924',
    '261073395',
    '261012914',
    '26957013',
    '',
    '26694640',
    '26629396',
    '26529704',
    '251551520',
    '251516128',
    '251476022',
    '',
    '251308637',
    '251292797',
    '251270273',
    '251261806',
    '251215165',
    '',
    '251175212',
    '251162480,251162479',
    '',
    '251072752',
    '251045749',
    '251033632',
    '251009306,251009305',
    '251007604',
    '251007418',
    '25949460',
    '',
    '25812739',
    '25691153',
    '25580980',
    '25539240',
    '241534750',
    '241513583',
    '',
    '241391138',
    '241307365',
    '241263137',
    '241261560',
    '241151907',
    '241150620,241150619',
    '',
    '241079647',
    '241043918',
    '241028778',
    '241004013',
    '24887338',
    '24697126',
    '24589273',
    '231474727',
    '231446672',
    '',
    '',
    '',
    '231353271',
    '231250232',
    '231227513',
    '231219629',
    '231120817',
    '231117680,231117679',
    '',
    '231055712',
    '231013863',
    '231004825',
    '23959944',
    '23870940',
    '23691192',
    '23579250',
    '221454708',
    '221422024',
    '221335705',
    '',
    '',
    '221236771',
    '221224876,221224875',
    '221215349',
    '221211814',
    '221114089',
    '221055079',
    '221025423',
    '221014293',
    '221006926',
    '22966735',
    '22871457',
    '',
    '22698888',
    '22624090',
    '22619634',
    '22513872',
    '211481750',
    '211442425',
    '211427795',
    '211384117',
    '211333532',
    '211158924',
    '',
    '211118633',
    '211118609',
    '211118566',
    '',
    '211105155',
    '211090960',
    '211082698',
    '211026781',
    '211016750',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '211011986,211011985',
    '211009461,211009460',
    '',
    '',
    '',
    '21818361,21818360',
    '',
    '21650363',
    '21567672,21567673',
    '21567368'],
   'items': ['',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',

In [13]:
print(json_submissions["filings"].keys())
print(json_submissions["filings"]["recent"].keys())

# every key contains the list, each list is of equal length and same index represent same filings
# accessionNumber[0]  filingDate[0]  form[0]  primaryDocument[0]  → all one filing
# accessionNumber[1]  filingDate[1]  form[1]  primaryDocument[1]  → all one filing
print(type(json_submissions["filings"]["recent"]["accessionNumber"]))

# type of forms filed by the company
print(set(json_submissions["filings"]["recent"]["form"]))

dict_keys(['recent', 'files'])
dict_keys(['accessionNumber', 'filingDate', 'reportDate', 'acceptanceDateTime', 'act', 'form', 'fileNumber', 'filmNumber', 'items', 'core_type', 'size', 'isXBRL', 'isInlineXBRL', 'isXBRLNumeric', 'primaryDocument', 'primaryDocDescription'])
<class 'list'>
{'24F-2NT', 'N-CSR', 'NPORT-P', 'N-CEN', 'CORRESP', '40-17G/A', 'N-PX', '40-17G', '4', 'N-2', 'EFFECT', 'N-2/A', 'N-23C3A', '486APOS', '4/A', 'SC 13D', '40-APP', '3', 'N-CSRS', '424B3', '40-APP/A', 'N-8A', 'DEL AM', 'SC 13G', 'SC 13G/A', '486BPOS'}

In [14]:
# Find indices where form is one of the required forms
target_forms = ["N-CSR", "N-CSRS"]
# target_forms = ["10-K", "10-Q"]
json_submissions_recent = json_submissions["filings"]["recent"]

indices_target_forms = []
for i, form in enumerate(json_submissions_recent["form"]):
    if form in target_forms:
        indices_target_forms.append(i)

print("Found at indices:", indices_target_forms)
print("Total found:", len(indices_target_forms))

Found at indices: [3, 10, 25, 35, 47, 52, 66, 71, 84, 92]
Total found: 10

In [15]:
# the filings are sorted by filing date in descending order
for idx in indices_target_forms:
    print(
        json_submissions_recent["form"][idx],
        "|",
        json_submissions_recent["filingDate"][idx],
        "|",
        json_submissions_recent["reportDate"][idx],
        "|",
        json_submissions_recent["accessionNumber"][idx],
        "|",
        json_submissions_recent["primaryDocument"][idx]
    )

N-CSR | 2026-06-08 | 2026-03-31 | 0001213900-26-066323 | ea0290403-01_ncsr.htm
N-CSRS | 2025-12-05 | 2025-09-30 | 0001213900-25-118509 | ea0264802-01_ncsrs.htm
N-CSR | 2025-06-09 | 2025-03-31 | 0001213900-25-052549 | ea0241375-01_ncsr.htm
N-CSRS | 2024-12-09 | 2024-09-30 | 0001213900-24-106844 | ea0220876-01_ncsrs.htm
N-CSR | 2024-06-07 | 2024-03-31 | 0001213900-24-050670 | ea0205199-01_ncsr.htm
N-CSRS | 2023-12-08 | 2023-09-30 | 0001213900-23-094292 | ea165252_ncsrs.htm
N-CSR | 2023-06-09 |  | 0001213900-23-047761 | ea154416_ncsr.htm
N-CSRS | 2022-12-09 | 2022-09-30 | 0001398344-22-024397 | fp0080845-2_ncsrs.htm
N-CSR | 2022-06-09 | 2022-03-31 | 0001398344-22-011833 | fp0076916_ncsr.htm
N-CSRS | 2021-12-09 | 2021-09-30 | 0001398344-21-023692 | fp0070618_ncsrs.htm

# Download the filing

## 1. Single Filing

In [18]:
# accession = "0001213900-26-066324"
accession = '0001398344-26-004777'
parts = accession.split("-")

print("Filer ID:", parts[0]) # who submitted it (filing agent or company)
print("Year:", parts[1]) # year of filing
print("Sequence:", parts[2]) # sequential number that year

Filer ID: 0001398344
Year: 26
Sequence: 004777

In [19]:
accession_clean = accession.replace("-", "")
cik_plain = str(int(company_cik))  # remove leading zeros for archive URL

print("Clean accession:", accession_clean)
print("Plain CIK:", cik_plain)

Clean accession: 000139834426004777
Plain CIK: 1504234

### 1a. Finding the primary doc from the listing directory

In [20]:
url_filing = f"https://www.sec.gov/Archives/edgar/data/{cik_plain}/{accession_clean}/index.json"
resp_filing = requests.get(url=url_filing, headers=headers)
json_filing = resp_filing.json()
resp_filing.text

'{"directory":{"item":[{"last-modified": "2026-03-06 16:42:02","name":"0001398344-26-004777-index-headers.html","type":"text.gif","size":""},{"last-modified": "2026-03-06 16:42:02","name":"0001398344-26-004777-index.html","type":"text.gif","size":""},{"last-modified": "2026-03-06 16:42:02","name":"0001398344-26-004777.txt","type":"text.gif","size":""},{"last-modified": "2026-03-06 16:42:02","name":"0001398344-26-004777-xbrl.zip","type":"compressed.gif","size":"1046295"},{"last-modified": "2026-03-06 16:42:02","name":"bgx-20251231.xsd","type":"text.gif","size":"10794"},{"last-modified": "2026-03-06 16:42:02","name":"bgx-20251231_def.xml","type":"text.gif","size":"17202"},{"last-modified": "2026-03-06 16:42:02","name":"bgx-20251231_lab.xml","type":"text.gif","size":"24064"},{"last-modified": "2026-03-06 16:42:02","name":"bgx-20251231_pre.xml","type":"text.gif","size":"16656"},{"last-modified": "2026-03-06 16:42:02","name":"FilingSummary.xml","type":"text.gif","size":"2281"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_01.jpg","type":"image2.gif","size":"154079"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_02.jpg","type":"image2.gif","size":"69569"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_03.jpg","type":"image2.gif","size":"35425"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_04.jpg","type":"image2.gif","size":"18959"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_05.jpg","type":"image2.gif","size":"74847"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_06.jpg","type":"image2.gif","size":"37089"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_07.jpg","type":"image2.gif","size":"19749"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_08.jpg","type":"image2.gif","size":"73255"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_09.jpg","type":"image2.gif","size":"27958"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_10.jpg","type":"image2.gif","size":"19077"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_11.jpg","type":"image2.gif","size":"266315"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_ex9912c.htm","type":"text.gif","size":"21203"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_ex99906cert.htm","type":"text.gif","size":"7359"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_ex99cert.htm","type":"text.gif","size":"17529"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_ex99code.htm","type":"text.gif","size":"27106"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_ncsrixbrl.htm","type":"text.gif","size":"3484613"},{"last-modified": "2026-03-06 16:42:02","name":"fp0097125-1_ncsrixbrl_htm.xml","type":"text.gif","size":"517075"},{"last-modified": "2026-03-06 16:42:02","name":"MetaLinks.json","type":"text.gif","size":"159805"},{"last-modified": "2026-03-06 16:42:02","name":"R1.htm","type":"text.gif","size":"774774"},{"last-modified": "2026-03-06 16:42:02","name":"report.css","type":"text.gif","size":"2767"},{"last-modified": "2026-03-06 16:42:02","name":"Show.js","type":"text.gif","size":"1085"}],"name":"\\/Archives\\/edgar\\/data\\/1504234\\/000139834426004777","parent-dir":"\\/Archives\\/edgar\\/data\\/1504234"}}'

In [21]:
print(json_filing["directory"].keys())
print(json_filing["directory"]["item"])
print(json_filing["directory"]["name"])
print(json_filing["directory"]["parent-dir"])

dict_keys(['item', 'name', 'parent-dir'])
[{'last-modified': '2026-03-06 16:42:02', 'name': '0001398344-26-004777-index-headers.html', 'type': 'text.gif', 'size': ''}, {'last-modified': '2026-03-06 16:42:02', 'name': '0001398344-26-004777-index.html', 'type': 'text.gif', 'size': ''}, {'last-modified': '2026-03-06 16:42:02', 'name': '0001398344-26-004777.txt', 'type': 'text.gif', 'size': ''}, {'last-modified': '2026-03-06 16:42:02', 'name': '0001398344-26-004777-xbrl.zip', 'type': 'compressed.gif', 'size': '1046295'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'bgx-20251231.xsd', 'type': 'text.gif', 'size': '10794'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'bgx-20251231_def.xml', 'type': 'text.gif', 'size': '17202'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'bgx-20251231_lab.xml', 'type': 'text.gif', 'size': '24064'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'bgx-20251231_pre.xml', 'type': 'text.gif', 'size': '16656'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'FilingSummary.xml', 'type': 'text.gif', 'size': '2281'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_01.jpg', 'type': 'image2.gif', 'size': '154079'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_02.jpg', 'type': 'image2.gif', 'size': '69569'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_03.jpg', 'type': 'image2.gif', 'size': '35425'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_04.jpg', 'type': 'image2.gif', 'size': '18959'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_05.jpg', 'type': 'image2.gif', 'size': '74847'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_06.jpg', 'type': 'image2.gif', 'size': '37089'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_07.jpg', 'type': 'image2.gif', 'size': '19749'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_08.jpg', 'type': 'image2.gif', 'size': '73255'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_09.jpg', 'type': 'image2.gif', 'size': '27958'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_10.jpg', 'type': 'image2.gif', 'size': '19077'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_11.jpg', 'type': 'image2.gif', 'size': '266315'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_ex9912c.htm', 'type': 'text.gif', 'size': '21203'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_ex99906cert.htm', 'type': 'text.gif', 'size': '7359'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_ex99cert.htm', 'type': 'text.gif', 'size': '17529'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_ex99code.htm', 'type': 'text.gif', 'size': '27106'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_ncsrixbrl.htm', 'type': 'text.gif', 'size': '3484613'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'fp0097125-1_ncsrixbrl_htm.xml', 'type': 'text.gif', 'size': '517075'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'MetaLinks.json', 'type': 'text.gif', 'size': '159805'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'R1.htm', 'type': 'text.gif', 'size': '774774'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'report.css', 'type': 'text.gif', 'size': '2767'}, {'last-modified': '2026-03-06 16:42:02', 'name': 'Show.js', 'type': 'text.gif', 'size': '1085'}]
/Archives/edgar/data/1504234/000139834426004777
/Archives/edgar/data/1504234

In [22]:
# here primary doc is oklo-20260331.htm
for file in json_filing["directory"]["item"]:
    print(file["name"], "|", file["type"], "|", file["size"])

0001398344-26-004777-index-headers.html | text.gif |
0001398344-26-004777-index.html | text.gif |
0001398344-26-004777.txt | text.gif |
0001398344-26-004777-xbrl.zip | compressed.gif | 1046295
bgx-20251231.xsd | text.gif | 10794
bgx-20251231_def.xml | text.gif | 17202
bgx-20251231_lab.xml | text.gif | 24064
bgx-20251231_pre.xml | text.gif | 16656
FilingSummary.xml | text.gif | 2281
fp0097125-1_01.jpg | image2.gif | 154079
fp0097125-1_02.jpg | image2.gif | 69569
fp0097125-1_03.jpg | image2.gif | 35425
fp0097125-1_04.jpg | image2.gif | 18959
fp0097125-1_05.jpg | image2.gif | 74847
fp0097125-1_06.jpg | image2.gif | 37089
fp0097125-1_07.jpg | image2.gif | 19749
fp0097125-1_08.jpg | image2.gif | 73255
fp0097125-1_09.jpg | image2.gif | 27958
fp0097125-1_10.jpg | image2.gif | 19077
fp0097125-1_11.jpg | image2.gif | 266315
fp0097125-1_ex9912c.htm | text.gif | 21203
fp0097125-1_ex99906cert.htm | text.gif | 7359
fp0097125-1_ex99cert.htm | text.gif | 17529
fp0097125-1_ex99code.htm | text.gif | 27106
fp0097125-1_ncsrixbrl.htm | text.gif | 3484613
fp0097125-1_ncsrixbrl_htm.xml | text.gif | 517075
MetaLinks.json | text.gif | 159805
R1.htm | text.gif | 774774
report.css | text.gif | 2767
Show.js | text.gif | 1085

### 1b. Using the submissions data primary doc

In [23]:
primary_doc = json_submissions_recent["primaryDocument"][indices_target_forms[0]]
print(primary_doc)

url_primary_doc = f"https://www.sec.gov/Archives/edgar/data/{cik_plain}/{accession_clean}/{primary_doc}"

resp_primary_doc = requests.get(url_primary_doc, headers={"User-Agent": "Zain zain@unicusresearch.com"})
print("Status:", resp_primary_doc.status_code)
print("File size (bytes):", len(resp_primary_doc.content))
print("First 500 chars:")
print(resp_primary_doc.text[:500])

fp0097125-1_ncsrixbrl.htm
Status: 200
File size (bytes): 3484613
First 500 chars:
<?xml version='1.0' encoding='ASCII'?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrldt="http://xbrl.org/2005/xbrldt" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2013/inlineXBRL" xmlns:ixt="http://www.xbrl.org/inlineXBRL/transformation/2015-02-26" xmlns:ixt-sec="http://w

In [24]:
filepath = Path("/home/cognify/Downloads")
# filepath = Path("../cliffwater_coporate_lending_fund/CCLFX_Shareholder_reports/2025-09-30/filings/")
filepath.mkdir(parents=True, exist_ok=True)

In [25]:
# Save the file
# filename = f"OKLO_{json_submissions_recent['form'][indices_target_forms[0]]}_{json_submissions_recent['filingDate'][indices_target_forms[0]]}.htm"
filename = Path(f"{filepath}/{primary_doc}")

with open(filename, "wb") as f:
    f.write(resp_primary_doc.content)

## 2. Multiple Filings

In [16]:
cik_plain = str(int(company_cik))  # remove leading zeros for archive URL
print("Plain CIK:", cik_plain)

Plain CIK: 1842754

In [17]:
# dir_filings = Path("../stone_ridge_trust5_lendex/LENDEX_Shareholder_reports/2026-02-28/filings")
dir_filings = Path("/home/cognify/Downloads/SEC_Funds/CPCF_Files")
dir_filings.mkdir(parents=True, exist_ok=True)

In [18]:
count = 1
for idx in indices_target_forms:
    print(f"Downloading index: {idx}")

    primary_doc = json_submissions_recent["primaryDocument"][idx]
    accession = json_submissions_recent["accessionNumber"][idx]
    accession_clean = accession.replace("-", "")

    url_primary_doc = f"https://www.sec.gov/Archives/edgar/data/{cik_plain}/{accession_clean}/{primary_doc}"
    print(f"Primary Doc URL: {url_primary_doc}")

    resp_primary_doc = requests.get(url_primary_doc, headers={"User-Agent": "Zain zain@unicusresearch.com"})
    print("Status:", resp_primary_doc.status_code)

    # Save the file
    # filename = f"LENDEX_{json_submissions_recent['form'][idx]}_{json_submissions_recent['reportDate'][idx]}_{count}.htm"
    filename = primary_doc
    filepath = Path(dir_filings/filename)
    with open(filepath, "wb") as f:
        f.write(resp_primary_doc.content)

    count += 1

Downloading index: 3
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000121390026066323/ea0290403-01_ncsr.htm
Status: 200
Downloading index: 10
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000121390025118509/ea0264802-01_ncsrs.htm
Status: 200
Downloading index: 25
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000121390025052549/ea0241375-01_ncsr.htm
Status: 200
Downloading index: 35
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000121390024106844/ea0220876-01_ncsrs.htm
Status: 200
Downloading index: 47
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000121390024050670/ea0205199-01_ncsr.htm
Status: 200
Downloading index: 52
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000121390023094292/ea165252_ncsrs.htm
Status: 200
Downloading index: 66
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000121390023047761/ea154416_ncsr.htm
Status: 200
Downloading index: 71
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000139834422024397/fp0080845-2_ncsrs.htm
Status: 200
Downloading index: 84
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000139834422011833/fp0076916_ncsr.htm
Status: 200
Downloading index: 92
Primary Doc URL: https://www.sec.gov/Archives/edgar/data/1842754/000139834421023692/fp0070618_ncsrs.htm
Status: 200